spring:
  application:
    name: JPA_H2_demo
  profiles:
    active: default
  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/test
#    url: jdbc:h2:tcp://localhost:8080/~/test
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true
        id:
          new_generator_mappings: true
